# Generated by Django 4.1.3 on 2022-12-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户唯一id')),
                ('uin', models.CharField(max_length=20, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=32, verbose_name='密码')),
                ('nick', models.CharField(max_length=20, verbose_name='昵称')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('avatar', models.CharField(default='', max_length=256, verbose_name='头像')),
                ('utype', models.IntegerField(default=0, verbose_name='用户权限')),
                ('reg_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='最后登录时间')),
            ],
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False, verbose_name='微博唯一id')),
                ('text', models.TextField(max_length=140, verbose_name='微博内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('wtype', models.IntegerField(default=0, verbose_name='微博状态')),
                ('view', models.IntegerField(default=0, verbose_name='阅读量')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.user', verbose_name='发表者用户id')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, verbose_name='评论唯一id')),
                ('text', models.TextField(max_length=140, verbose_name='微博内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.user', verbose_name='评论者用户id')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.weibo', verbose_name='被评论微博唯一id')),
            ],
        ),
    ]
